// This file will be auto-generated by `supabase gen types typescript`
// For now, we define a manual version matching our schema

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          first_name: string | null;
          last_name: string | null;
          avatar_url: string | null;
          national_id: string | null;
          preferred_language: string;
          preferred_currency: string;
          home_airport: string | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          national_id?: string | null;
          preferred_language?: string;
          preferred_currency?: string;
          home_airport?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          national_id?: string | null;
          preferred_language?: string;
          preferred_currency?: string;
          home_airport?: string | null;
          onboarding_completed?: boolean;
          updated_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          description: string | null;
          website: string | null;
          status: string;
          settings: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          description?: string | null;
          website?: string | null;
          status?: string;
          settings?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          logo_url?: string | null;
          description?: string | null;
          website?: string | null;
          status?: string;
          settings?: Record<string, unknown> | null;
        };
      };
      tiers: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          level: number;
          description: string | null;
          color: string | null;
          icon: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          level: number;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
          created_at?: string;
        };
        Update: {
          company_id?: string;
          name?: string;
          level?: number;
          description?: string | null;
          color?: string | null;
          icon?: string | null;
        };
      };
      user_memberships: {
        Row: {
          id: string;
          user_id: string;
          company_id: string;
          tier_id: string;
          status: string;
          request_source: string;
          requested_at: string;
          approved_at: string | null;
          approved_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id: string;
          tier_id: string;
          status?: string;
          request_source?: string;
          requested_at?: string;
          approved_at?: string | null;
          approved_by?: string | null;
        };
        Update: {
          status?: string;
          tier_id?: string;
          approved_at?: string | null;
          approved_by?: string | null;
        };
      };
      privileges: {
        Row: {
          id: string;
          company_id: string;
          title: string;
          description: string | null;
          category: string;
          usage_model: string;
          discount_percentage: number | null;
          quota_limit: number | null;
          quota_period: string | null;
          eligible_tier_ids: string[];
          provider_id: string | null;
          validity_start: string | null;
          validity_end: string | null;
          terms: string | null;
          status: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          title: string;
          description?: string | null;
          category: string;
          usage_model?: string;
          discount_percentage?: number | null;
          quota_limit?: number | null;
          quota_period?: string | null;
          eligible_tier_ids?: string[];
          provider_id?: string | null;
          validity_start?: string | null;
          validity_end?: string | null;
          terms?: string | null;
          status?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          category?: string;
          usage_model?: string;
          discount_percentage?: number | null;
          quota_limit?: number | null;
          quota_period?: string | null;
          eligible_tier_ids?: string[];
          provider_id?: string | null;
          validity_start?: string | null;
          validity_end?: string | null;
          terms?: string | null;
          status?: string;
          sort_order?: number;
        };
      };
      user_privilege_usage: {
        Row: {
          id: string;
          user_id: string;
          privilege_id: string;
          membership_id: string;
          used_at: string;
          transaction_id: string | null;
          period_key: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          privilege_id: string;
          membership_id: string;
          used_at?: string;
          transaction_id?: string | null;
          period_key: string;
        };
        Update: {};
      };
      providers: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: string;
          logo_url: string | null;
          description: string | null;
          api_base_url: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: string;
          logo_url?: string | null;
          description?: string | null;
          api_base_url?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          type?: string;
          logo_url?: string | null;
          description?: string | null;
          api_base_url?: string | null;
          status?: string;
        };
      };
      trips: {
        Row: {
          id: string;
          user_id: string;
          origin_city: string;
          origin_country: string;
          origin_airport_code: string | null;
          destination_city: string;
          destination_country: string;
          destination_airport_code: string | null;
          flight_number: string | null;
          departure_date: string;
          return_date: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          origin_city: string;
          origin_country: string;
          origin_airport_code?: string | null;
          destination_city: string;
          destination_country: string;
          destination_airport_code?: string | null;
          flight_number?: string | null;
          departure_date: string;
          return_date?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          origin_city?: string;
          origin_country?: string;
          origin_airport_code?: string | null;
          destination_city?: string;
          destination_country?: string;
          destination_airport_code?: string | null;
          flight_number?: string | null;
          departure_date?: string;
          return_date?: string | null;
          status?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          user_id: string;
          trip_id: string | null;
          type: string;
          status: string;
          provider_id: string;
          privilege_id: string | null;
          amount: number;
          currency: string;
          discount_amount: number;
          flow_data: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          trip_id?: string | null;
          type: string;
          status?: string;
          provider_id: string;
          privilege_id?: string | null;
          amount: number;
          currency?: string;
          discount_amount?: number;
          flow_data?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: string;
          amount?: number;
          discount_amount?: number;
          flow_data?: Record<string, unknown> | null;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          data: Record<string, unknown> | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          data?: Record<string, unknown> | null;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          read?: boolean;
        };
      };
      campaigns: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          image_url: string | null;
          type: string;
          linked_privilege_id: string | null;
          priority: number;
          start_date: string;
          end_date: string;
          target_tier_ids: string[];
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          image_url?: string | null;
          type: string;
          linked_privilege_id?: string | null;
          priority?: number;
          start_date: string;
          end_date: string;
          target_tier_ids?: string[];
          status?: string;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          image_url?: string | null;
          type?: string;
          priority?: number;
          start_date?: string;
          end_date?: string;
          target_tier_ids?: string[];
          status?: string;
        };
      };
      marketplace_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          icon: string | null;
          description: string | null;
          sort_order: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          icon?: string | null;
          description?: string | null;
          sort_order?: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          icon?: string | null;
          description?: string | null;
          sort_order?: number;
          status?: string;
        };
      };
      esim_activations: {
        Row: {
          id: string;
          transaction_id: string;
          package_name: string;
          data_amount: string;
          duration_days: number;
          destination_country: string;
          flight_number: string | null;
          activation_type: string;
          qr_code_data: string | null;
          activation_link: string | null;
          provider_package_id: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          package_name: string;
          data_amount: string;
          duration_days: number;
          destination_country: string;
          flight_number?: string | null;
          activation_type?: string;
          qr_code_data?: string | null;
          activation_link?: string | null;
          provider_package_id?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          status?: string;
        };
      };
      transfer_reservations: {
        Row: {
          id: string;
          transaction_id: string;
          provider_name: string;
          vehicle_type: string;
          origin_address: string;
          origin_lat: number;
          origin_lng: number;
          destination_address: string;
          dest_lat: number;
          dest_lng: number;
          pickup_time: string;
          estimated_duration_min: number;
          price: number;
          currency: string;
          reservation_ref: string;
          driver_name: string | null;
          driver_rating: number | null;
          driver_phone: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          provider_name: string;
          vehicle_type: string;
          origin_address: string;
          origin_lat?: number;
          origin_lng?: number;
          destination_address: string;
          dest_lat?: number;
          dest_lng?: number;
          pickup_time: string;
          estimated_duration_min?: number;
          price: number;
          currency?: string;
          reservation_ref: string;
          driver_name?: string | null;
          driver_rating?: number | null;
          driver_phone?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          status?: string;
          driver_name?: string | null;
          driver_phone?: string | null;
        };
      };
      insurance_policies: {
        Row: {
          id: string;
          transaction_id: string;
          provider_name: string;
          plan_name: string;
          coverage_amount: number;
          coverage_currency: string;
          premium_price: number;
          premium_currency: string;
          policy_number: string;
          policy_pdf_url: string | null;
          beneficiary_name: string;
          travel_start: string;
          travel_end: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          provider_name: string;
          plan_name: string;
          coverage_amount: number;
          coverage_currency: string;
          premium_price: number;
          premium_currency: string;
          policy_number: string;
          policy_pdf_url?: string | null;
          beneficiary_name: string;
          travel_start: string;
          travel_end: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          status?: string;
        };
      };
      service_passes: {
        Row: {
          id: string;
          transaction_id: string;
          service_type: string;
          venue_name: string;
          location: string;
          access_code: string;
          access_code_type: string;
          valid_from: string;
          valid_until: string;
          guest_count: number;
          used_at: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          transaction_id: string;
          service_type: string;
          venue_name: string;
          location: string;
          access_code: string;
          access_code_type?: string;
          valid_from: string;
          valid_until: string;
          guest_count?: number;
          used_at?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          status?: string;
          used_at?: string | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
